// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1556616530);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 25);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "60.6.1");
user_pref("extensions.lastPlatformVersion", "60.6.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "4cc9e6c6-b9bf-48b6-a2c6-6d363b14186");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("toolkit.telemetry.cachedClientID", "d0688b18-40df-4948-b6df-c105faf863bf");
user_pref("toolkit.telemetry.previousBuildID", "20190325095516");
