theme = "modern"

#[icons]
icons = "awesome"
#[icons.overrides]
#cpu = "  "
#gpu = "  "
#memory_mem = "  " 
#net_wired = ""
#net_down = "  "

[[block]]
block = "sound"
on_click = "pavucontrol"

#[[block]]
#block = "bluetooth"
#mac = "00:09:A7:48:CD:D3"
#label = " E8"

#[[block]]
#block = "bluetooth"
#mac = "00:16:94:39:D1:EA"
#label = " PXC"

[[block]]
block = "net"
device = "eth0"
hide_missing = true
hide_inactive = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1
format = "{utilization}% {frequency}"

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 3
#format = "{max}°C"
#chip = "k10temp-*"
#warning = 75

#[[block]]
#block = "nvidia_gpu"
#show_memory = false
#interval = 1

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"


[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"
